# ppa:ethereum is not yet available on 22.04
FROM ubuntu:20.04
ARG USERNAME="hardhat"
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=nonintercative
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  bash-completion \
  build-essential \
  ca-certificates \
  curl \
  git \
  gpg-agent \
  jq \
  libpython3-dev \
  libudev-dev \
  locales-all locales \
  python3 \
  python3-pip \
  python3-setuptools \
  python3.8-venv \
  software-properties-common \
  sudo \
  vim \
  wget \
  xdot \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y ppa:ethereum/ethereum && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  solc \
  ethereum \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update \
  && apt-get install -y nodejs \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN npm install --global yarn

ENV VIRTUAL_ENV_PATH_MYTHRIL=/opt/venv/mythril
RUN python3 -m venv $VIRTUAL_ENV_PATH_MYTHRIL
ENV PATH="$VIRTUAL_ENV_PATH_MYTHRIL/bin:$PATH"
COPY src/requirements.mythril.txt .
RUN source $VIRTUAL_ENV_PATH_MYTHRIL/bin/activate
RUN pip install -r requirements.mythril.txt --no-input --no-cache-dir

ENV VIRTUAL_ENV_PATH_SLITHER=/opt/venv/slither
RUN python3 -m venv $VIRTUAL_ENV_PATH_SLITHER
ENV PATH="$VIRTUAL_ENV_PATH_SLITHER/bin:$PATH"
COPY src/requirements.slither.txt .
RUN source $VIRTUAL_ENV_PATH_SLITHER/bin/activate
RUN pip install -r requirements.slither.txt --no-input --no-cache-dir

RUN cd $VIRTUAL_ENV_PATH_SLITHER/bin && \
  wget https://github.com/crytic/echidna/releases/download/v2.0.0/echidna-test-2.0.0-Ubuntu-18.04.tar.gz \
  -O echidna.tar.gz \
  && tar -xzf echidna.tar.gz \
  && rm echidna.tar.gz

ARG ROOT_PASS=ROOT

# This is for crytic-compile binary
ENV PATH="${PATH}:${HOME}/.local/bin"

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN useradd -m hardhat
RUN mkdir -p /home/hardhat/.config/hardhat-nodejs && \
  chown -R 1000:1000 /home/hardhat/.config/hardhat-nodejs

# This line allows gh actions to run without the need for
# root permissions
RUN mkdir -p /github/home/.cache/hardhat-nodejs && \
  chown -R 1000:1000 /github/home/.cache/hardhat-nodejs

# This is required by matplotlib in mythril venv
RUN mkdir -p /home/hardhat/.config/matplotlib && \
  chown -R 1000:1000 /home/hardhat/.config/matplotlib 

ADD https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/3eb6693a91b1aa5b3863d087de1d189b72eeeec8/create-env-example.sh /scripts/create-env-example.sh
ADD https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/7df99dbbeb8ee4d14396be043aef4fbf8fb42ce5/.bashrc /home/$USERNAME/.bashrc
ADD https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/d227102e3630a93f8eafcb4d2a5a053d2ae04415/.inputrc /home/$USERNAME/.inputrc

USER $USERNAME

# TODO make this work
# CMD ["/bin/bash"]
