name: build-and-push

on:
  push:
    tags:
      - "**.**.**"
      - experiment/**/**/**
    paths:
      - src/**
      - .github/workflows/build-and-push.yml
  workflow_dispatch:

env:
  CONTAINER_NAME: ethereum-devcontainer
  CACHE_TO_DEST: /tmp/.buildx-cache-new
  CACHE_FROM_SRC: /tmp/.buildx-cache

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v25
        with:
          files: |
            src/**
            .github/workflows/build-and-push.yml

      - name: Declare run state
        id: run-state
        run: |
          if [ ${{ github.ref_type }} == tag ] && \
            ( \
              [ ${{ steps.changed_files.outputs.any_modified }} == true ] || \
              [ ${{ github.event_name }} == workflow_dispatch ] \
            );
          then
            echo "run_docker_build=true" >> $GITHUB_OUTPUT
            echo "::debug::Docker build will carry out as expected."
          else
            cancel_message="Docker build is cancelled as build requirements haven't been met."
            echo "run_docker_build=false" >> $GITHUB_OUTPUT
            echo "::debug::$cancel_message"
            echo "$cancel_message"
          fi

      - name: Variables
        id: variables
        shell: bash
        run: |
          image_name=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}
          repo_tag="${{ github.ref_name }}"
          image_tag="${repo_tag//\//-}"
          dev_image_tag=${image_tag}
          image_ref="${image_name}:${image_tag}"
          dev_image_ref="${image_name}:${dev_image_tag}"
          short_image_ref="${{ env.CONTAINER_NAME }}:${image_tag}"
          short_dev_image_ref="${{ env.CONTAINER_NAME }}:${dev_image_tag}"

          for i in \
            image_name \
            image_tag \
            dev_image_tag \
            image_ref \
            dev_image_ref \
            short_image_ref \
            short_dev_image_ref; 
          do 
            echo "$i=${!i}" >> $GITHUB_OUTPUT; 
          done

      - name: Set up Docker Buildx
        if: steps.run-state.outputs.run_docker_build == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.run-state.outputs.run_docker_build == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container ${{ steps.variables.outputs.short_image_ref }}
        if: steps.run-state.outputs.run_docker_build == 'true'
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.variables.outputs.image_ref }}
          file: src/Dockerfile.dev
          push: true
          pull: false
          cache-from: type=local,src=${{ env.CACHE_FROM_SRC }}
          cache-to: type=local,mode=max,dest=${{ env.CACHE_TO_DEST }}
          build-args: |
            ROOT_PASS=${{ secrets.DOCKER_IMAGE_ROOT_PASS }}

      - name: Build devcontainer ${{ steps.variables.outputs.short_dev_image_ref }}
        if: steps.run-state.outputs.run_docker_build == 'true'
        id: devcontainer_build
        uses: devcontainers/ci@v0.2
        env:
          IMAGE_NAME: ${{ steps.variables.outputs.image_name }}
          IMAGE_TAG: ${{ steps.variables.outputs.image_tag }}
        with:
          imageName: ${{ steps.variables.outputs.image_name }}
          imageTag: ${{ steps.variables.outputs.dev_image_tag }}
          subFolder: src
          runCmd: /scripts/devcontainer-check.sh

      - name: Push devcontainer ${{ steps.variables.outputs.short_dev_image_ref }}
        if: steps.run-state.outputs.run_docker_build == 'true'
        run: docker push ${{ steps.variables.outputs.dev_image_ref }}

      - name: Set Docker Hub description
        if: steps.run-state.outputs.run_docker_build == 'true'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ steps.variables.outputs.image_name }}
          short-description: Ethereum devcontainers
          readme-filepath: src/DOCKER_README.md

      - name: Move cache
        run: |
          rm -rf ${{ env.CACHE_FROM_SRC }}
          if [ -d ${{ env.CACHE_FROM_SRC }} ];
          then
            mv ${{ env.CACHE_TO_DEST }} ${{ env.CACHE_FROM_SRC }}
          fi
